/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encriptamiento;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrmEncriptar extends javax.swing.JFrame {

    Encriptar encriptar;
    int clave;
    String texto;

    /**
     * Creates new form FrmEncriptar
     */
    public FrmEncriptar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtClave = new javax.swing.JTextField();
        txtEncriptado = new javax.swing.JTextField();
        txtDesencripat = new javax.swing.JTextField();
        txtTetxto = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClave.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtClave.setBorder(null);
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, 20));

        txtEncriptado.setEditable(false);
        txtEncriptado.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtEncriptado.setBorder(null);
        getContentPane().add(txtEncriptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 198, 210, 30));

        txtDesencripat.setEditable(false);
        txtDesencripat.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtDesencripat.setBorder(null);
        getContentPane().add(txtDesencripat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 210, 20));

        txtTetxto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtTetxto.setBorder(null);
        getContentPane().add(txtTetxto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 140, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        try {
            clave = Integer.parseInt(txtClave.getText());
            texto = txtTetxto.getText();
            encriptar = new Encriptar(clave, texto);
            txtEncriptado.setText(encriptar.getCriptado());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ingresar correctamente los datos","Mensaje",2);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            txtDesencripat.setText(encriptar.getDesencriptado(encriptar.getCriptado()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ingresar correctamente los datos","Mensaje",2);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDesencripat;
    private javax.swing.JTextField txtEncriptado;
    private javax.swing.JPasswordField txtTetxto;
    // End of variables declaration//GEN-END:variables
}
